name: Deploy

on: push

jobs: 
    build: 
        runs-on: ubuntu-latest

        steps:
            - name: Print variable
              run: echo "The value of the variable is ${{ secrets.MY_VARIABLE }}"
     
            - name: checkout
              uses: actions/checkout@v4 
              
            - name: setup
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test
            
            - name: build page
              run: npm run build             
    deploy:
        # if: ${{ always() }}    #si hubiese un error en el test continua igual.
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Deploy to production
              run: echo "Deploying to production environment"
              
        
    